export default [
  {
    id: 1,
    img: "./images/card1pic.jpg",
    rating: 5.0,
    reviewCount: 6,
    country: "INDIA",
    title: "Life of lessons with Neeraj chopra",
    price: 136,
    openSpots: 0,
  },
  {
    id: 2,
    img: "./images/card2pic.jpg",
    rating: 4.5,
    reviewCount: 7,
    country: "India",
    title: "Life of lessons with PV Sindhu",
    price: 90,
    openSpots: 1,
    location: "online",
  },
  {
    id: 3,
    img: "./images/card3pic.jpg",
    rating: 5.6,
    reviewCount: 10,
    country: "India",
    title: "Life of lessons with Bajrang Punia",
    price: 150,
    openSpots: 2,
  },
  {
    img: "./images/card4pic.jpg",
    rating: 4.5,
    reviewCount: 7,
    country: "India",
    title: "Life of lessons with Ravi Kumar",
    price: 90,
  },
  {
    img: "./images/card1pic.jpg",
    rating: 5.6,
    reviewCount: 10,
    country: "INDIA",
    title: "Life lessons with Neeraj chopra",
    price: 150,
  },
  {
    img: "./images/card1pic.jpg",
    rating: 5.0,
    reviewCount: 6,
    country: "INDIA",
    title: "Life lessons with Neeraj chopra",
    price: 136,
  },
];